# Generated by Django 4.0.1 on 2022-01-19 08:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpManager',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='漏洞名称')),
                ('vulnid', models.CharField(db_column='vulnid', max_length=32, verbose_name='漏洞编号')),
                ('category', models.CharField(choices=[('1', 'WEB漏洞'), ('2', '系统漏洞'), ('3', '其他漏洞')], max_length=2, verbose_name='漏洞类型')),
                ('fileobj', models.FileField(null=True, upload_to='MyCMS/exp/', verbose_name='工具上传')),
                ('expflag', models.BooleanField(db_column='expflag', default=False, verbose_name='是否有EXP')),
                ('description', tinymce.models.HTMLField(db_column='description', verbose_name='漏洞描述')),
                ('timestamp', models.DateField(db_column='deadline', verbose_name='创建日期')),
                ('command', models.TextField(db_column='command', null=True, verbose_name='执行命令')),
            ],
            options={
                'verbose_name': '验证工具',
                'verbose_name_plural': '验证工具',
            },
        ),
    ]
