# Generated by Django 4.0.1 on 2022-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpManager', '0003_alter_expmanager_vulnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expmanager',
            name='fileobj',
            field=models.FileField(null=True, upload_to='ExpManager/exp/', verbose_name='负载上传'),
        ),
    ]
