# Generated by Django 4.0.1 on 2022-03-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(choices=[('1', 'Virustotal接口'), ('2', '钉钉接口'), ('3', 'Github接口'), ('4', '钟馗之眼接口'), ('5', '佛法接口'), ('6', '系统线程数'), ('7', '系统IP地址'), ('8', '系统域名配置')], max_length=2, unique=True, verbose_name='漏洞类型')),
                ('user', models.TextField(db_column='user', null=True, verbose_name='账号')),
                ('value', models.TextField(db_column='value', null=True, verbose_name='Token令牌')),
                ('ipaddress', models.GenericIPAddressField(db_column='ipaddress', default='127.0.0.1', null=True, verbose_name='账号邮箱')),
                ('domain', models.TextField(db_column='email', default='apollo.local', null=True, verbose_name='账号邮箱')),
                ('timestamp', models.DateField(db_column='deadline', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '配置信息',
                'verbose_name_plural': '配置信息',
            },
        ),
    ]
