# Generated by Django 4.0.1 on 2022-03-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='domain',
            field=models.TextField(db_column='domain', default='apollo.local', verbose_name='系统域名'),
        ),
        migrations.AlterField(
            model_name='config',
            name='ipaddress',
            field=models.GenericIPAddressField(db_column='ipaddress', default='127.0.0.1', verbose_name='系统地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('1', 'Virustotal接口'), ('2', '钉钉接口'), ('3', 'Github接口'), ('4', '钟馗之眼接口'), ('5', '佛法接口'), ('6', '系统线程数'), ('7', '系统IP地址'), ('8', '系统域名配置')], max_length=2, unique=True, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.TextField(db_column='user', verbose_name='账号'),
        ),
    ]
