# Generated by Django 4.0.1 on 2022-03-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_alter_config_domain_alter_config_ipaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='domain',
            field=models.TextField(blank=True, db_column='domain', default='apollo.local', null=True, verbose_name='系统域名'),
        ),
        migrations.AlterField(
            model_name='config',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, db_column='ipaddress', default='127.0.0.1', null=True, verbose_name='系统地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.TextField(blank=True, db_column='user', null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(db_column='value', verbose_name='Token令牌'),
        ),
    ]
