# Generated by Django 4.0.1 on 2022-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0005_config_port_alter_config_name_alter_config_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('1', 'VT接口'), ('2', '钉钉接口'), ('3', 'Github接口'), ('4', '钟馗接口'), ('5', '佛法接口'), ('6', '线程数'), ('7', '系统地址'), ('8', '系统域名'), ('9', '常用端口'), ('10', '关键端口')], max_length=2, unique=True, verbose_name='配置名称'),
        ),
    ]
